---
title: "Modelling"
author: "Gauthami"
date: "5/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
library(corrplot)
library(e1071)
#library(xgboost)
library(stringr)
library(lubridate)
library(tm)
library(rms)
library(glmnet)
library(pROC)
library(doMC)
library(kernlab)
```

```{r}
library(dplyr)
library(ggplot2)
library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
library(corrplot)
library(e1071)
library(kernlab)
library(stringr)
library(lubridate)
library(pROC)

```

```{r}
data =read.csv("~/Desktop/Assignement/InputData_New.csv",stringsAsFactors=FALSE)

```

```{r}
names(data)
data$X.2 <- NULL
data$X.1 <- NULL
data$X <- NULL
data$pullDate <- NULL
names(data)
```



```{r}
set.seed(6438)

train_index <- 
  caret::createDataPartition(y = data$loan_status, times = 1, 
                             p = .8, list = FALSE)

train <- data[train_index, ]
test <- data[-train_index, ]


```


```{r}
train_down <- 
  caret::downSample(x = train[, !(names(train) %in% c("loan_status"))], 
                    y = as.factor(train$loan_status), yname = "loan_status")

base::prop.table(table(train_down$loan_status))
```



```{r}
train_down$loan_status = ifelse(train_down$loan_status == "TRUE","yes","no")
train_down$loan_status = as.factor(train_down$loan_status)
levels(train_down$loan_status)
```



```{r}
loan_status = train_down$loan_status
dummy_model = dummyVars(loan_status ~ .,train_down,fullRank = TRUE)
train_down = as.data.frame(predict(dummy_model,train_down))
train_down$loan_status = loan_status
rm(loan_status)
```
```{r}
loan_status = test$loan_status
dummy_model1 = dummyVars(loan_status ~ .,test,fullRank = TRUE)
test = as.data.frame(predict(dummy_model1,test))
test$loan_status = loan_status
rm(loan_status)
```

```{r}
test$loan_status = ifelse(test$loan_status == "TRUE","yes","no")
test$loan_status = as.factor(test$loan_status)
levels(test$loan_status)
```

```{r}
test$loan_status <- as.factor(test$loan_status)
is.factor(test$loan_status)
```

```{r}
dim(test)
```

```{r}
100*nrow(test %>% filter(loan_status=="no"))/nrow(test)
```




```{r}
getIndexsOfColumns <- function(t,column_names){
    return(match(column_names,colnames(t)))
}
```


```{r}
set.seed(200)
#down sampling again so than we get more info when stacking
samp = downSample(train_down[-getIndexsOfColumns(train_down, c( "loan_status") )],as.factor(train_down$loan_status),yname="loan_status")
#choose small data for tuning 
train_index_tuning = createDataPartition(as.factor(samp$loan_status),p = 0.05,list=FALSE,times=1)
#choose small data for re-train
train_index_training = createDataPartition(as.factor(samp$loan_status),p = 0.1,list=FALSE,times=1)
```


```{r}
svmGrid = expand.grid(
                .sigma = as.numeric(sigest(loan_status ~.,data = samp[train_index_tuning,],scaled=FALSE)),
                .C = c(0.1,1,10)
                )

```

```{r}
getIndexsOfColumns <- function(t,column_names){
    return(match(column_names,colnames(t)))
}
ctrl <- trainControl(method = "cv",
    summaryFunction = twoClassSummary,
    classProbs = TRUE,
    number = 3
    )
```


```{r}
levels(samp$loan_status)
```

```{r}
svmTuned = train(
    samp[train_index_tuning,-getIndexsOfColumns(samp,"loan_status")],
    y =as.factor( samp[train_index_tuning,"loan_status"]),
    method = "svmRadial",
    tuneGrid = svmGrid,
    metric = "ROC",
    trControl = ctrl,
    preProcess = NULL,
    scaled = FALSE,
    fit = FALSE)

plot(svmTuned)

svmTuned
```

```{r}
svmTuned$results$sigma
```

```{r}
svm_model = ksvm(loan_status ~ .,
                 data = samp[train_index_training,],
                 kernel = "rbfdot",
                 kpar = list(sigma=0.00000000049988),
                 C = 10.0,
                 prob.model = TRUE,
                 scaled = FALSE)


```






```{r}
predict_loan_status_svm = predict(svm_model,test,type="probabilities")

```


```{r}
predict_loan_status = as.data.frame(predict_loan_status_svm)$yes
```

```{r}
nrow(predict_loan_status_svm )
```

```{r}
CF_Matrix1<-table(test$loan_status, predict_loan_status > 0.5)
```


```{r}
results <- ifelse(predict_loan_status >  0.5, "yes", "no")
misClasificError1 <- mean(results != test$loan_status)
```



```{r}
#Accuracy Rate
print(paste(' Accuracy rate',1-misClasificError1))

#_Misclassification Error rate_
print(paste(' Error rate',misClasificError1))

##Confusion Matrix
print("Confusion Matrix "); CF_Matrix1

#sensitivity
print("Sensitivity ");CF_Matrix1[1,1]/(CF_Matrix1[1,1] + CF_Matrix1[2,1])


```

```{r}

```

```{r}
rocCurve_svm = roc(response = test$loan_status,
               predictor = predict_loan_status_svm)

```


```{r}
auc_curve = auc(rocCurve_svm)
auc_curve 


```


```{r}


plot(rocCurve_svm,legacy.axes = TRUE,print.auc = TRUE,col="red",main="ROC(SVM)")
```






